#!/bin/sh
#deploy="false"
deploy="true"

image=MSAClient
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t dhruvikatrodiya/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push dhruvikatrodiya/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag dhruvikatrodiya/${image}:1.0-SNAPSHOT dhruvikatrodiya/${image}:latest
        docker push dhruvikatrodiya/${image}:latest
    fi
fi